### ISSUE TITLE
why does vim-ipython preview window close after leaving insert-mode?

### ISSUE THREAD

**Issue by reckoner** [wilywampa/vim-ipython#2]
When editing a Python file in the buffer, the `vim-ipython` preview window closes after leaving insert mode in the main file buffer. How can I leave the `vim-ipython` open even while editing the main buffer window that has the Python file?

Thanks!

**Comment by wilywampa** [comment]
Are you referring to the preview window showing completion information or the vim-ipython window showing sent/received IPython commands/output?

**Comment by reckoner** [comment]
The vim-ipython window is the window that keeps closing on me. The one with the sent/received commands is what I'm referring to. Thanks!

**Comment by wilywampa** [comment]
What's the output of `:autocmd InsertLeave`?

**Comment by reckoner** [comment]
See below:

    :autocmd InsertLeave
    --- Auto-Commands ---
    PrevInsertComplete  InsertLeave
        *         call PrevInsertComplete#Record#Do()
    jedi_call_signatures  InsertLeave
        <buffer=1>
                  call jedi#clear_call_signatures()
                  if exists('b:_jedi_orig_updatetime') |   let &updatetime = b:_jedi_orig_upda
    tetime |   unlet b:_jedi_orig_updatetime | endif
    InsertLeave
        <buffer=1>
                  if pumvisible() == 0|pclose|endif
                  call s:RunPyflakes()
    jedi_call_signatures  InsertLeave
        <buffer=2>
                  call jedi#clear_call_signatures()
                  if exists('b:_jedi_orig_updatetime') |   let &updatetime = b:_jedi_orig_upda
    tetime |   unlet b:_jedi_orig_updatetime | endif
    InsertLeave
        <buffer=2>
                  if pumvisible() == 0|pclose|endif
                  call s:RunPyflakes()


I think

    if pumvisible() == 0|pclose|endif

is the problem.

**Comment by wilywampa** [comment]
Thanks, and agreed. You can find out what is creating the autocommand using `:verbose au InsertEnter` and I bet you'll find an option to disable it.

**Comment by reckoner** [comment]
Thanks! I got it.
