### ISSUE TITLE
Is it possible to use vim-ipython with only python3 support?

### ISSUE THREAD

**Issue by xxyxxyxyx1** [wilywampa/vim-ipython#5]
Many of my plugins require python3, and it isn't possible to compile vim with both versions, except on windows. This plugin seems to require it. I am running `-python +python3`, and I cannot start vim-ipython. 

When I open a .py file and type `:IPython`, I get:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/mathe/.vim/bundle/vim-ipython/ftplugin/python/vim_ipython.py", line 209, in km_from_string
    km.load_connection_file()
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/jupyter_client/conne
ct.py", line 494, in load_connection_file
    info = json.load(f)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 299, in lo
ad
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in lo
ads
    return _default_decoder.decode(s)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in dec
ode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw
_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

(I am not certain this is related to python2/3, that is my only guess). 

Thank you

**Comment by DerWeh** [comment]
I already tried myself to port the code to python 3, but there seem to be a few subtle points.

If you want a quick workaround, just use [Neovim](https://github.com/neovim/neovim). In basically all cases it is a drop-in replacement for Vim, with a lot of additional goodies.  
Support for both versions is as easy as

```
pip2 install neovim
pip3 install neovim
```

Neovim provides an Appimage, so just download the 10MB and give it a shot.

-----------------------
Additionally Neovim has a built-in terminal. So you can actually run an `ipython console` in a split buffer of vim. If you start the `monitor` in that split before running the console you have a splendid experience. 

Just do
```
:split|terminal
i (insert mode)
python2 ~/path/to/plugin/vim-ipython/monitor.py&|ipython console
```
the console itself can be Python3.

**Comment by wilywampa** [comment]
My build of Vim is also `-python` and `+python3` and it works fine. Can you figure out what connection file it's trying to read and paste the contents of that file? Should be something like:

```json
{
  "shell_port": 54459,
  "iopub_port": 54460,
  "stdin_port": 54461,
  "control_port": 54462,
  "hb_port": 54463,
  "ip": "127.0.0.1",
  "key": "8a76a8fb-819ea446299c1f9fb42084ec",
  "transport": "tcp",
  "signature_scheme": "hmac-sha256",
  "kernel_name": ""
}
```

**Comment by xxyxxyxyx1** [comment]
@wilywampa, I am sorry to report that I cannot provide more information: I switched to neovim and wiped normal vim back to defaults. I probably should have come back to close this issue sooner. 

Thank you for maintaining this fork though!
